"""Canales lineales de referencia para la grilla argentina, inspirados en Flow.

No contiene streams, contraseñas ni URLs. No garantiza que un proveedor ofrezca
la señal: el selector exige una prueba de video positiva antes de publicarla.
Grillas y packs cambian por zona, fecha y suscripción. No incluye apps ni VOD.
"""

FLOW_CHANNELS = [
    ("Argentina · Noticias", "Metro", ("Metro TV", "Metro Argentina")),
    ("Argentina · Noticias", "Argentina/12", ("Argentina 12", "Ar 12", "Ar12")),
    ("Argentina · Noticias", "Diputados TV", ("Diputados TV Argentina", "DTV Diputados")),
    ("Argentina · Noticias", "Senado Argentina", ("Senado TV Argentina", "Senado TV")),
    ("Argentina · Noticias", "CNN en Español", ("CNN Español", "CNN en Espanol")),
    ("Argentina · Noticias", "DNews", ("D News", "DirecTV News")),
    ("Argentina · Noticias", "Euronews Español", ("Euronews en Español", "Euronews")),
    ("Argentina · Noticias", "France 24 Español", ("France 24 en Español", "France24 Español")),
    ("Argentina · Noticias", "Somos La Plata", ("Somos La Plata HD",)),
    ("Argentina · Noticias", "Somos Rosario", ()),
    ("Argentina · Noticias", "Somos Santa Fe", ()),
    ("Argentina · Noticias", "Somos Salta-Jujuy", ("Somos Salta Jujuy",)),
    ("Argentina · Noticias", "Somos Mar del Plata", ()),
    ("Argentina · Noticias", "Somos El Valle", ()),
    ("Argentina · Deportes", "El Garage TV", ("Garage TV", "Garage TV Latin America")),
    ("Argentina · Deportes", "América Sports", ("America Sports",)),
    ("Argentina · Deportes", "PX Sports", ("PXTV Sports",)),
    ("Argentina · Deportes", "Flow Sports", ("Flow Sports 1",)),
    ("Argentina · Deportes", "Flow Sports 2", ("Flow Sports 02",)),
    ("Argentina · Deportes", "Flow Sports 3", ("Flow Sports 03",)),
    ("Argentina · Deportes", "TNT Sports Argentina", ("TNT Sports Premium", "TNT Sports Flow")),
    ("Argentina · Deportes", "Golf Channel", ("Golf Channel Latin America", "Golf Channel Latinoamérica")),
    ("Argentina · Cultura", "Canal (á)", ("Canal á", "Canal A Cultura")),
    ("Argentina · Cultura", "UNLP TV", ("UNLP.TV", "TV Universidad Nacional de La Plata", "TVU La Plata")),
    ("Argentina · Cultura", "Canal Encuentro Internacional", ("Encuentro Internacional",)),
    ("Argentina · Entretenimiento", "Mix TV", ("MixTV Argentina",)),
    ("Argentina · Entretenimiento", "Argentinísima Satelital", ("Argentinisima Satelital", "Argentinisima TV")),
    ("Argentina · Entretenimiento", "Canal C", ("Canal C Argentina", "CanalC Argentina")),
    ("Argentina · Entretenimiento", "Telemax", ("Telemax Argentina",)),
    ("Argentina · Entretenimiento", "Sun Channel", ("Sun Channel Latinoamérica",)),
    ("Argentina · Entretenimiento", "Canal Luz", ("CanalLuz", "Canal Luz Argentina")),
    ("Argentina · Entretenimiento", "Santa María", ("Santa Maria TV",)),
    ("Argentina · Entretenimiento", "EWTN", ("EWTN Español", "EWTN Latinoamérica")),
    ("Argentina · Entretenimiento", "KZO", ("KZO Entertainment",)),
    ("Argentina · Entretenimiento", "Canal Orbe 21", ("Orbe21", "Orbe 21")),
    ("Argentina · Regionales", "Somos AMBA", ("Somos AMBA HD",)),
    ("Argentina · Regionales", "Somos San Nicolás", ("Somos San Nicolas",)),
    ("Argentina · Regionales", "Somos San Pedro", ()),
    ("Argentina · Regionales", "Somos Azul", ()),
    ("Argentina · Regionales", "Somos Chacabuco", ()),
    ("Argentina · Regionales", "TeleJunín", ("TeleJunin",)),
    ("Argentina · Regionales", "Canal Diez Junín", ("Canal Diez Junin",)),
    ("Argentina · Regionales", "Rafaela Noticias TV", ()),
    ("TV · Ficción", "HBO Pop", ("HBO POP",)),
    ("TV · Ficción", "Universal Premiere", ("Universal Premier",)),
    ("TV · Ficción", "Universal Comedy", ()),
    ("TV · Ficción", "Universal Crime", ()),
    ("TV · Ficción", "Universal Reality", ()),
    ("TV · Ficción", "Cine.ar", ("Cine AR", "Cinear", "Cine.Ar TV")),
    ("TV · Ficción", "Volver", ("Canal Volver", "Volver TV")),
    ("TV · Ficción", "USA Network", ("USA TV",)),
    ("TV · Ficción", "AMC Series", ()),
    ("TV · Ficción", "A3Series", ("A3 Series", "Atreseries")),
    ("TV · Ficción", "Sony Movies", ()),
    ("TV · Ficción", "Eurochannel", ("Euro Channel",)),
    ("TV · Ficción", "A3Cine", ("A3 Cine", "Atrescine")),
    ("TV · Ficción", "DHE", ("DHE HD", "DHE Channel")),
    ("TV · Ficción", "Pasiones", ("Pasiones TV",)),
    ("TV · Ficción", "Telemundo Internacional", ("Telemundo International",)),
    ("TV · Ficción", "TNT Novelas", ("TNT Novelas HD",)),
    ("TV · Ficción", "TLNovelas", ("Telenovelas", "TL Novelas")),
    ("Infantiles", "DreamWorks Channel", ("Dreamworks TV",)),
    ("Infantiles", "Cartoonito", ("Cartoonito Latinoamérica",)),
    ("Infantiles", "Baby TV", ("BabyTV",)),
    ("Infantiles", "Nick Jr.", ("Nick Jr", "Nick Junior")),
    ("Infantiles", "Plim Plim", ("El Canal del Payaso Plim Plim", "Canal Plim Plim")),
    ("Infantiles", "Kidoo", ("Kidoo TV",)),
    ("Documentales", "Discovery Turbo", ()),
    ("Documentales", "Discovery Theater", ("Discovery Theatre", "Discovery Theater HD")),
    ("Documentales", "Discovery World", ("Discovery World HD",)),
    ("Documentales", "Investigation Discovery", ("ID Investigation Discovery", "ID Discovery")),
    ("Documentales", "History 2", ("H2 History", "History2")),
    ("Documentales", "Discovery Home & Health", ("Discovery Home and Health", "Home and Health")),
    ("Entretenimiento", "TLC", ("TLC Latinoamérica",)),
    ("Entretenimiento", "HGTV", ("HGTV Latinoamérica",)),
    ("Entretenimiento", "Hola TV", ("¡Hola! TV", "HOLA TV")),
    ("Entretenimiento", "E!", ("E Entertainment Television", "E! Entertainment Television")),
    ("Música", "Vorterix", ("Vorterix TV",)),
    ("Música", "Allegro HD", ("Allegro",)),
    ("Música", "HTV", ("HTV Música",)),
    ("Música", "CM", ("CM Canal de la Música", "CM El Canal de la Música")),
    ("Música", "Flow Music", ()),
    ("Música", "Quiero Música", ("Quiero Música en Mi Idioma", "Quiero Musica en mi Idioma")),
]
